---

# FIRST HOST
- hosts: node01b-mainnet
  vars:
    # CHANGE THESE VARIABLES ACCORDING TO YOUR SETUP
    solana_cli_path: /root/.local/share/solana/install/active_release/bin
    solana_keys_path: /root/solana
    ledger_path: /root/solana/ledger
    tower_path: /root/solana/ledger

  tasks:
  - name: Get tower filename
    shell: find {{tower_path}} -name tower-*.bin
    register: tower_stdout

  - name: Save tower filename
    set_fact:
      tower_filepath: "{{tower_stdout.stdout_lines[0]}}"
      tower_filename: "{{tower_stdout.stdout_lines[0] | basename}}"

  - name: Transfer Secondary Node ID to a Backup-Node (Non-Voting)
    shell: |
      solana-validator --ledger {{ledger_path}}/ wait-for-restart-window --identity {{solana_keys_path}}/secondary-identity.json --min-idle-time 5 --skip-new-snapshot-check
      solana-validator --ledger {{ledger_path}}/ set-identity {{solana_keys_path}}/secondary-unstaked-identity.json
    environment:
      PATH: $PATH:{{solana_cli_path}}

  - name: Move Secondary ID symlink to unstaked
    file:
      src: "{{solana_keys_path}}/secondary-unstaked-identity.json"
      dest: "{{solana_keys_path}}/secondary-identity.json"
      state: link

  - name: Fetch the tower from Secondary Node
    run_once: yes
    fetch: src="{{tower_filepath}}" dest=/tmp/ flat=yes


# SECOND HOST
- hosts: node01-mainnet
  vars:
    # CHANGE THESE VARIABLES ACCORDING TO YOUR SETUP
    solana_cli_path: /root/.local/share/solana/install/active_release/bin
    solana_keys_path: /root/solana
    ledger_path: /mnt/ledger
    tower_path: /mnt/ramdisk/tower

    # CHANGE `solana-host-secondary` BELOW (MATCH THE CONTENT OF THE host FILE)
    tower_filename: "{{hostvars['node01b-mainnet']['tower_filename']}}"

  tasks:
  - name: Copy the tower to Primary Node
    copy: src=/tmp/{{tower_filename}} dest={{tower_path}}

  - name: Set Primary Node ID to staked-identity
    shell: |
      solana-validator --ledger {{ledger_path}}/ set-identity --require-tower {{solana_keys_path}}/staked-identity.json
    environment:
      PATH: $PATH:{{solana_cli_path}}

  - name: Move Primary ID symlink to staked
    file:
      src: "{{solana_keys_path}}/staked-identity.json"
      dest: "{{solana_keys_path}}/primary-identity.json"
      state: link

- hosts: 127.0.0.1
  connection: local
  vars:
    # CHANGE `solana-host-secondary` BELOW (MATCH THE CONTENT OF THE host FILE)
    tower_filename: "{{hostvars['node01b-mainnet']['tower_filename']}}"
  tasks:
    - name: /tmp/<tower> Cleanup
      file: path=/tmp/{{tower_filename}} state=absent
